apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: k8s-test-ip
    networking.gke.io/managed-certificates: my-certificate
spec:
  backend:
    serviceName: my-service
    servicePort: first-port
  # tls:
  #   - secretName: tls-secret
  # rules:
  #   - host: k8s.shapes.ai
  #     http:
  #       paths:
  #         - backend:
  #             serviceName: my-service
  #             servicePort: first-port
